---
site_name: Citrix Director SDK
site_description: Citrix Director SDK 参考指南
theme_dir: citrix-sdk
repo_url: 'https://github.com/ajitchelat/AppDNA-SDK.git'
markdown_extensions:
  - admonition
  - codehilite
  -
    toc:
      anchorlink: true
pages:
  -
    Index: index.md
